/*  =========================================================================
    fty_certificate_generator_rest_classes - private header file

    Copyright (C) 2014 - 2019 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_CERTIFICATE_GENERATOR_REST_CLASSES_H_INCLUDED
#define FTY_CERTIFICATE_GENERATOR_REST_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty-certificate-generator-rest.h"

//  Opaque class structures to allow forward references
#ifndef HELPERS_CERTIFICATE_GENERATOR_REST_T_DEFINED
typedef struct _helpers_certificate_generator_rest_t helpers_certificate_generator_rest_t;
#define HELPERS_CERTIFICATE_GENERATOR_REST_T_DEFINED
#endif
#ifndef REST_SERVICES_GET_T_DEFINED
typedef struct _rest_services_get_t rest_services_get_t;
#define REST_SERVICES_GET_T_DEFINED
#endif
#ifndef REST_SERVICE_GET_T_DEFINED
typedef struct _rest_service_get_t rest_service_get_t;
#define REST_SERVICE_GET_T_DEFINED
#endif
#ifndef REST_CERTIFICATE_POST_T_DEFINED
typedef struct _rest_certificate_post_t rest_certificate_post_t;
#define REST_CERTIFICATE_POST_T_DEFINED
#endif
#ifndef REST_CERTIFICATE_GET_T_DEFINED
typedef struct _rest_certificate_get_t rest_certificate_get_t;
#define REST_CERTIFICATE_GET_T_DEFINED
#endif
#ifndef REST_CERTIFICATE_PUT_T_DEFINED
typedef struct _rest_certificate_put_t rest_certificate_put_t;
#define REST_CERTIFICATE_PUT_T_DEFINED
#endif
#ifndef REST_CSR_POST_T_DEFINED
typedef struct _rest_csr_post_t rest_csr_post_t;
#define REST_CSR_POST_T_DEFINED
#endif
#ifndef REST_CSR_GET_T_DEFINED
typedef struct _rest_csr_get_t rest_csr_get_t;
#define REST_CSR_GET_T_DEFINED
#endif
#ifndef REST_CSR_DELETE_T_DEFINED
typedef struct _rest_csr_delete_t rest_csr_delete_t;
#define REST_CSR_DELETE_T_DEFINED
#endif

//  Extra headers

//  Internal API

#include "helpers_certificate_generator_rest.h"
#include "rest_services_GET.h"
#include "rest_service_GET.h"
#include "rest_certificate_POST.h"
#include "rest_certificate_GET.h"
#include "rest_certificate_PUT.h"
#include "rest_csr_POST.h"
#include "rest_csr_GET.h"
#include "rest_csr_DELETE.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_CERTIFICATE_GENERATOR_REST_BUILD_DRAFT_API

//  Self test for private classes
FTY_CERTIFICATE_GENERATOR_REST_PRIVATE void
    fty_certificate_generator_rest_private_selftest (bool verbose, const char *subtest);

#endif // FTY_CERTIFICATE_GENERATOR_REST_BUILD_DRAFT_API

#endif
